# .circleci/config.yml
version: 2.1
jobs:
  make-testflight-build:
    macos:
      xcode: 14.3.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: testflight
    steps:
      - checkout
      - run: cd testmono; bundle install
      - run:
          name: Fastlane
          command: cd testmono; bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

workflows:
  build-testflight:
    jobs:
      - make-testflight-build:
          filters:
            branches:
              only: master
