# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  before_all do
    setup_circle_ci
  end
  

  desc "Development build"
  lane :development do
    match(type: "development")
    gym(
      scheme: "testmono",
      export_method: "development",
      export_xcargs: "-allowProvisioningUpdates",
      include_symbols: true,
      include_bitcode: false,
      clean: true,
      output_name: "testmono-development.ipa",
      export_options: {iCloudContainerEnvironment: 'Production'} 
    )
  end

  desc "Test Flight Build"
  lane :testflight do 
    match(type: "appstore")
    gym(
      scheme: "testmono",
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates",
      include_symbols: true,
      include_bitcode: false,
      clean: true,
      output_name: "testmono-development.ipa",
      export_options: {iCloudContainerEnvironment: 'Production'} 
    )
    # Upload to TestFlight
    pilot(
			skip_waiting_for_build_processing: true,
		  apple_id: "6450774016"
		)
  end
end
